server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Important for React Router SPA (Single Page Application)
    # Redirect all 404s to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
